#!/bin/sh
set -e


runOpenHAB() {
    docker rm --force openhab || true

    /usr/bin/docker run \
	  --name=openhab \
	  --net=host \
      -v /etc/localtime:/etc/localtime:ro \
      -v /etc/timezone:/etc/timezone:ro \
      -v /opt/openhab/conf:/openhab/conf \
      -v /opt/openhab/userdata:/openhab/userdata \
      -v /opt/openhab/addons:/openhab/addons \
      -e USER_ID=9001 \
      -e GROUP_ID=9001 \
      openhab/openhab:2.5.3-amd64-debian
}

# Run openHAB
runOpenHAB
