#!/bin/sh
set -e

# Load configs
CONFIG_FILE="/opt/openhab/docker/install.conf"

USER_ID="$(jq --raw-output '.USER_ID' ${CONFIG_FILE})"
GROUP_ID="$(jq --raw-output '.GROUP_ID' ${CONFIG_FILE})"
ARCH="$(jq --raw-output '.ARCH' ${CONFIG_FILE})"
OH_VERSION="$(jq --raw-output '.OH_VERSION' ${CONFIG_FILE})"

runOpenHAB() {
    docker rm --force openhab || true

    /usr/bin/docker run \
	  --name=openhab \
	  --net=host \
      -v /etc/localtime:/etc/localtime:ro \
      -v /etc/timezone:/etc/timezone:ro \
      -v /opt/openhab/conf:/openhab/conf \
      -v /opt/openhab/userdata:/openhab/userdata \
      -v /opt/openhab/addons:/openhab/addons \
      -e USER_ID=${USER_ID} \
      -e GROUP_ID=${GROUP_ID} \
      openhab/openhab:2.5.3-amd64-debian
}

# Run openHAB
runOpenHAB
